version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: backend_service

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    container_name: frontend_service
    depends_on:
      - backend
